import numpy as np
import pandas as pd
from pandas_datareader import data as pdr
import pathlib
import os
import yfinance as yf
import csv
import json
import sys
import time
from dateutil.parser import parse
from confluent_kafka import Producer
import socket
import pymysql
from elasticsearch import Elasticsearch
from base64 import encodebytes

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "kasi123"
from datetime import datetime


def geteSqlConnection(host,user,pwd,db):
    # Connect to the database
    connection = pymysql.connect(host=host,
                                 user=user,
                                 password=pwd,
                                 db=db)
    return connection
def getEsCLient():
    # Create the client instance
    client = Elasticsearch(
        "https://localhost:9200",
        verify_certs=False,
        basic_auth=("elastic", ELASTIC_PASSWORD)
    )
    return client